# EventStream â€” SAM Deployment Configuration
version = 0.1

[default.deploy.parameters]
stack_name = "eventstream"
resolve_s3 = true
s3_prefix = "eventstream"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=production AlertEmail=ops@example.com"
tags = "Project=EventStream ManagedBy=SAM"
